# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
# Position Controllers ---------------------------------------
#  joint_position_controller:
#    type: position_controllers/JointPositionController
#    joint: Joint
#    pid: {p: 100.0, i: 0.01, d: 10.0}
#IMU
imu_sensor_controller:
  type: imu_sensor_controller/ImuSensorController
  name: Imu
  publish_rate: 50

####
diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'l_wheel_joint'
  right_wheel : 'r_wheel_joint'
  publish_rate: 50.0
  enable_odom_tf: true

  pose_covariance_diagonal : [0.000, 0.000, 0.0, 0.0, 0.0, 0.0]
  twist_covariance_diagonal: [0.000, 0.000, 0.0, 0.0, 0.0, 0.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 1.0
  wheel_radius : 0.3

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  # Base frame_id
  base_frame_id: base_link # base_footprint #default base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0  # m/s
      min_velocity           : -1.0 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.8  # m/s^2
      min_acceleration       : -0.8 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.7  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.5  # rad/s^2
